baseurl = "http://www.digitalstefan.com"
title = "DigitalStefan"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

#disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Stefan Holmes"
  info = "Google Tag Manager Nerd"
  description = "DigitalStefan's Little Testing Website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2023

  enableTwemoji = false

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  url = "https://github.com/StefanHolmes/"
[[params.social]]
  name = "Mastodon"
  icon = "fa fa-mastodon fa-2x"
  url = "https://fosstodon.org/@digitalstefan/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin-square fa-2x"
  url = "https://www.linkedin.com/in/digitalstefan/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"